### ISSUE TITLE
Syntax error with comments between parameters

### ISSUE THREAD

**Issue by john-tornblom** [xtuml/pyrsl#13]
To facilitate analysis of comments in source code, the current RSL grammar contain production rules for capturing comments. This makes the grammar more complicated, and is currently incomplete. For example, comments before or between param declarations cause syntax error. I suggest we remove the comments from the grammar, and instead drop them during scanning in the tokenizer.

**Comment by john-tornblom** [comment]
Since the current API in pyrsl does not expose comments in the syntax tree, I recommend the change is introduced in both master and maintanence/1.0

**Comment by john-tornblom** [comment]
@cortlandstarrett I originally left this in the grammar for you specifically so you could detect relate/unrelate hints you've used in comments. Since the AST now include relate/unrelate nodes, I don't think this is needed anymore.

**Comment by cortlandstarrett** [comment]
It is true.  The more important comments are trailing line comments on
functions and parameter lines.  These allow me to specify return types and
parameter types.  But these are only used by a separate RSL2OAL converter.

**Comment by john-tornblom** [comment]
Ahh, right, you also provide hints on the return type. Parameter type of instances are included in master, but return types are trickier given the dynamic nature of the language.

**Comment by cortlandstarrett** [comment]
Correct.  We are generally making it a practice to avoid using the
structured return type (fragment) in lieu of returning an actually instance
reference.

**Comment by john-tornblom** [comment]
For early adopters, patch for maintenance/v1.0 available at:
    https://github.com/xtuml/pyrsl/tree/issues/13-syntax-error-with-comments-between-parameters

and corresponding binaries are available at:
    https://ci.appveyor.com/project/john-tornblom/pyrsl/build/artifacts

unit tests needs to be written before merged.

**Comment by john-tornblom** [comment]
fixed in f7a533d8afd27 (pyrsl-v2) and ff087028e89 (v1.0)
