### ISSUE TITLE
unrelate on reflexive modifies wrong element

### ISSUE THREAD

**Issue by keithbrown** [xtuml/pyrsl#14]
[q.sys.populate.arc.txt](https://github.com/xtuml/pyrsl/files/1476295/q.sys.populate.arc.txt)
In the 1.0 version of generator I am seeing a problem trying to build MicrowaveOven.  During the build we are sorting the domain functions across a reflexive.  This list management involves unrelating instances that are currently connected so we can then relate in the new instance we want to insert at the proper point. 

The problem is that when I unrelate instances in the middle of the list, the element at the head of the list is modified as well as the "previous" element in the middle of the list.  If I use direct assignment to 0 on the previous instead of the ".unrelate" then only the element I want to touch is modified and everything works.

Here is some output that shows the issue via print statement debugging:
```
...
q.sys.populate.arc: 2577:  INFO:  SKB: Inserting DefineOven
q.sys.populate.arc: 2585:  INFO:  ///// EMB: CancelCooking
q.sys.populate.arc: 2588:  INFO:  ///// EMB: CloseDoor
q.sys.populate.arc: 2588:  INFO:  ///// EMB: DecreasePower
q.sys.populate.arc: 2588:  INFO:  ///// EMB: IncreasePower
q.sys.populate.arc: 2588:  INFO:  ///// EMB: SpecifyCookingPeriod
q.sys.populate.arc: 2588:  INFO:  ///// EMB: StartCooking
q.sys.populate.arc: 2588:  INFO:  ///// EMB: TestSequence1
q.sys.populate.arc: 2607:  INFO:    SKB1: head CancelCooking next is 1459
q.sys.populate.arc: 2608:  INFO:    SKB1: prev DecreasePower next is 1457
q.sys.populate.arc: 2609:  INFO:    SKB: going to unrelate. prev is DecreasePower, cursor is IncreasePower
**q.sys.populate.arc: 2617:  INFO:    SKB3: head CancelCooking next is None**
q.sys.populate.arc: 2618:  INFO:    SKB3: prev DecreasePower next is None
q.sys.populate.arc: 2621:  INFO:    SKB: linking DefineOven before IncreasePower
q.sys.populate.arc: 2622:  INFO:    SKB4: head next is None
q.sys.populate.arc: 2625:  INFO:    SKB: linking DecreasePower before DefineOven
q.sys.populate.arc: 2626:  INFO:    SKB5: head next is None
q.sys.populate.arc: 2631:  INFO:  --- SKB: CancelCooking
q.sys.populate.arc: 2639:  INFO:  --- SKB: cursor is empty
q.sys.populate.arc: 2644:  INFO:  --- SKB: returning CancelCooking
q.sys.populate.arc: 2555:  INFO:  ***** AJB: CancelCooking
...
```
Full log here: [console_log.txt](https://github.com/xtuml/pyrsl/files/1476308/console_log.txt)

I also note that when processing the element that has the problem, the generator pauses for several seconds.

I'm attaching the q.sys.populate.arc that is used to demonstrate the problem.  To see the problem  on linux/mac you have to turn off mcmc by renaming to mcmc.no and then building MicrowaveOven.

**Comment by john-tornblom** [comment]
If a referential attribute is part of an identifier, the unrelate operation does not always work in pyrsl1 (e.g subtype/supertype cannot be unrelated). This has been addressed in pyrsl2 (currently master).
This behavior will not change in v1 since I am unable to fix this issue without altering the semantics for referential attributes (which breaks compatibility with other stuff). So, you have to choose between:

pyrsl v1) write-support for referential attributes, and partial support for unrelate operations
pyrsl v2) full support for unrelate operations, and read-only referential attributes

**Comment by keithbrown** [comment]
ok.  For now I will use v1 and write referentials directly and not use .unrelate
