### ISSUE TITLE
Short circuit evaluation

### ISSUE THREAD

**Issue by leviathan747** [xtuml/pyrsl#15]
I am using v1.0.0. Currently it does not support short circuit evaluation for boolean expressions. A common pattern is:
```
.select any foo from instances of FOO
.if ( ( not_empty foo ) and ( foo.Value == "some_value" ) )
  .// do some action
.end if
```
I am finding that I have to split this into two if statements:
```
.if ( not_empty foo )
  .if ( foo.Value == "some_value" )
    .// do some action
  .end if
.end if
```
otherwise I risk a "NoneType has no attribute Value" error.

**Comment by leviathan747** [comment]
take a look at this pull request: https://github.com/xtuml/pyrsl/pull/16

**Comment by john-tornblom** [comment]
Generally, short-circuiting expressions change semantics of a languages, e.g. when the other expression affects the program state. RSL does not support invoking functions, but I need to think about it for a while. In 2.0 it makes sense to include it though. I can't remember what old windows-only gen_erate.exe would do.

Thanks for the patch!

**Comment by leviathan747** [comment]
Just as another data point, OAL supports it as well. OAL does allow invoking functions, and OAL also has an assignment expression, so there are certainly bad things you can do if you are not careful :)

**Comment by john-tornblom** [comment]
Is the evaluation order defined in OAL, i.e. is it from left to right, or right to left?
I try to avoid code constructs like these to avoid ambiguities amongst model compilers that target different intermediate source languages.

**Comment by leviathan747** [comment]
I don't know of any OAL specification that explicitly states the order. However, MC-Java generates code that evaluates left to right and so Verifier enforces left to right evaluation. MC3020 also generates C that evaluates left to right. Both C and Java implement short-circuiting for the logical 'and' and 'or'.

**Comment by john-tornblom** [comment]
Oki, great. Perhaps its only pascal that doesnt use this trick :)

**Comment by john-tornblom** [comment]
merged with master (v2). For now, v1.0 will not get this change since it alters semantics and thus may break compatibility with existing archetype files
