### ISSUE TITLE
Set subtraction bug

### ISSUE THREAD

**Issue by leviathan747** [xtuml/pyrsl#17]
Given the schema:
```
CREATE TABLE A_CLASS (
  name STRING,
  num INTEGER
);
```
and the following archetype:
```
.create object instance foo1 of A_CLASS
.assign foo1.name = "foo1"
.assign foo1.num = 1
.create object instance foo2 of A_CLASS
.assign foo2.name = "foo2"
.assign foo2.num = 2
.create object instance foo3 of A_CLASS
.assign foo3.name = "foo3"
.assign foo3.num = 3
.create object instance foo4 of A_CLASS
.assign foo4.name = "foo4"
.assign foo4.num = 4
.// test '-'
.print "Testing inst_ref - inst_ref"
.assign all_the_foos = foo1 - foo1
.for each foo in all_the_foos
  .print "${foo.name}"
.end for
.// expected results:
.//
.print "Testing inst_ref - inst_ref_set"
.select many foos from instances of A_CLASS where ( selected.num <= 2 )
.assign all_the_foos = foo2 - foos
.for each foo in all_the_foos
  .print "${foo.name}"
.end for
.// expected results:
.//
.print "Testing inst_ref_set - inst_ref"
.select many foos from instances of A_CLASS where ( selected.num <= 2 )
.assign all_the_foos = foos - foo2
.for each foo in all_the_foos
  .print "${foo.name}"
.end for
.// expected results:
.// foo1
.//
.print "Testing inst_ref_set - inst_ref_set"
.select many foos1 from instances of A_CLASS
.select many foos2 from instances of A_CLASS where ( selected.num >= 3 )
.assign all_the_foos = foos1 - foos2
.for each foo in all_the_foos
  .print "${foo.name}"
.end for
.// expected results:
.// foo1
.// foo2
```
this invocation:
```
gen_erate.pyz -nopersist -import sets.sql -arch sets.arc 
```
produces the following output:
```
sets.arc: 14:  INFO:  Testing inst_ref - inst_ref
sets.arc: 21:  INFO:  Testing inst_ref - inst_ref_set
sets.arc: 23:  ERROR:  
Traceback  (most recent call last):
    File "/Users/levi/git/bridgepoint/doc-bridgepoint/notes/5007_set_operations/sets.arc", line 23
```
(Line 23 is the line that says `.assign all_the_foos = foo2 - foos`)

According to the documentation [here](http://pyrsl.readthedocs.io/en/master/language-reference.html#instances-and-sets), I would expect that when `foo2 - foos` is evaluated, `foo2` would be converted to an instance set containing just one instance and the subtraction would be calculated. Since `foos` here contains `foo1` and `foo2`, this evaluation should result in an empty set. I believe there should not be a python error.

**Comment by leviathan747** [comment]
By the way, this analysis was done with version 1.0.0 (currently shipped with BridgePoint)

**Comment by john-tornblom** [comment]
Thanks! The subtraction operator for sets was not tested very well. Test case was added and hopefully captures your problem. See https://ci.appveyor.com/project/john-tornblom/pyrsl/build/1.0.212/artifacts for .exe and pyz file (v1.0 branch).

I tested your example and it works. Let me know if the fix also works for the original problem that exposed the error.

**Comment by leviathan747** [comment]
Thanks for the quick reply and patch! That version solves my original problem, so I'll close the issue. I should have mentioned that this is not a blocker for BridgePoint. I was doing an analysis on adding set operations to OAL and wanted to make sure I had a firm understanding of what is supported in RSL.

**Comment by john-tornblom** [comment]
No worries, I try to fix straight forward bugs as soon as possible so I don't forget about them :)

btw, python has good documentation on set operators that you might find useful: https://docs.python.org/2/library/sets.html#set-objects As you'll see, python also support the symmetric difference operator (^) which might be considered for inclusion in AOL as well.
