### ISSUE TITLE
.select behavioral change between 2.0.1 and 2.1.0

### ISSUE THREAD

**Issue by keithbrown** [xtuml/pyrsl#23]
The behavior of .select has changed between 2.0.1 and 2.1.0 and now causes failures in the BridgePoint build using MC-Java.

Error output snippet from console:
```
     [exec] translate_oal.inc: 64:  INFO:  ************** generate binary operation values     *****************
     [exec] arch_utils.inc: 552:  INFO:  SKB - bridge hasSameModelRoot
     [exec] arch_utils.inc: 554:  INFO:    SKB - param = nrme1
     [exec] arch_utils.inc: 554:  INFO:    SKB - param = nrme2
     [exec] arch_utils.inc: 557:  ERROR:  select one from a set with cardinality 2
     [exec] Traceback  (most recent call last):
     [exec]     File "/Users/kbrown/git/bridgepoint/src/MC-Java/java.arc", line 540
     [exec]     File "/Users/kbrown/git/bridgepoint/src/MC-Java/translate_oal.inc", line 144
```

based on this code:
```
.// TODO SKB
.select many skb_bridgeParams related by bridge->S_BPARM[R21]
.print "SKB - bridge ${bridge.Name}"
.for each skb_bridgeParam in skb_bridgeParams
  .print "  SKB - param = ${skb_bridgeParam.Name}"
.end for
.// END TODO SKB
	.select one bridgeParam related by bridge->S_BPARM[R21] where (selected.Name == parameter.Name)
```

Was this intentional?

**Comment by john-tornblom** [comment]
Yes. In OAL, you would get a syntax error since R21 is a one to many association, and thus select any should be used, not select one...

**Comment by john-tornblom** [comment]
It has been a check for this in pyrsl for a while now, but no test case. When I added a test case, I noticed a bug :)

**Comment by john-tornblom** [comment]
I updated the experimental linter included with pyrsl to search for these typos:

> WARNING:rsl.lint:src/MC-Java/java.arc:85:select one navigation yields a set
> WARNING:rsl.lint:src/MC-Java/java.arc:1468:select one navigation yields a set
> WARNING:rsl.lint:src/MC-Java/schema_gen.arc:195:select one navigation yields a set
> WARNING:rsl.lint:src/MC-Java/schema_gen.arc:213:select one navigation yields a set
> WARNING:rsl.lint:src/MC-Java/schema_gen.arc:330:select one navigation yields a set
> WARNING:rsl.lint:src/MC-Java/schema_gen.arc:371:select one navigation yields a set

**Comment by john-tornblom** [comment]
Note that the runtime check produce an error only when the yielded set actually contains more than one instance. If you encountered this problem, it is likely you have some error, e.g. duplicate copies of the same instance,a missing/incomplete where-clause. But perhaps you don't really care which instance you get?
