### ISSUE TITLE
Instructions for creating runnable generator

### ISSUE THREAD

**Issue by keithbrown** [xtuml/pyrsl#8]
Somewhere there should be developer instructions that include information about how to create gen_erate.pyz and gen_erate.exe.
# Instructions for getting set up to develop and build new generator on Ubuntu:

```
# Fork xtuml/pyrsl and xtuml/pyxtuml github repositories to my user (here "keithbrown") account
$ sudo apt-get install python-ply
$ git clone https://github.com/keithbrown/pyxtuml.git
$ cd pyxtuml
$ sudo python setup.py install
$ git clone https://github.xtuml/keithbrown/pyrsl.git
$ cd pyrsl
$ sudo python setup.py install
# Create branch on pyxtuml (and pyrsl) as appropriate
# Make changes, commit and push them
$ cd <git>/pyrsl
$ ./package_pyz.sh -gituser <github username> -pyxtuml <git branch name> -pyrsl <git branch name>
# gen_erate.pyz is created
```

**Comment by keithbrown** [comment]
@john-tornblom , do you have instructions in rough form that you could drop in here until they find a permanent home in the docs?  Thanks.

**Comment by john-tornblom** [comment]
On Windows, install python 2.7 and git, then run:

$ python -m pip install --user ply
$ python -m pip install --user pyxtuml
$ python -m pip install --user py2exe_py2
$ git clone https://github.com/xtuml/pyrsl
$ cd pyrsl
$ python setup.py py2exe -O2 -c -b1 -p xtuml,rsl

for a Windows appveyor script, see https://github.com/xtuml/pyrsl/blob/master/appveyor.yml

**Comment by john-tornblom** [comment]
fixed in https://github.com/xtuml/pyrsl/commit/6be0ac927e8172c573ca256becc957453870daa7
