### ISSUE TITLE
relate/unrelate using

### ISSUE THREAD

**Issue by leviathan747** [xtuml/pyrsl#9]
Support relate and unrelate statements for associative relationships. There is a workaround to use two relate statements to relate the "one" and "other" classes to the associative class separately.

**Comment by john-tornblom** [comment]
Good idea! I've added support for it in https://github.com/john-tornblom/pyrsl/commit/498dbe14f15f9b78c521910d2e1a7e13b01d0042

I'm not sure if I got the phrases order correct though. I always get that one wrong.
A second pair of eyes on that is probably needed!

**Comment by leviathan747** [comment]
This looks good! I'm also not sure about the phrase order. I will try to take a look at it more closely.

**Comment by john-tornblom** [comment]
this is part of master now, closing
